# Generated by Django 6.0.7 on 2026-10-05 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_address', models.EmailField(blank=True, max_length=254)),
                ('to_address', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
