# Generated by Django 6.0.7 on 2026-10-09 00:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('pickup', 'Store pickup'), ('rider', 'Rider delivery'), ('agent', 'Pickup agent (e.g. Pickup Mtaani)')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('eta', models.CharField(blank=True, help_text="Shown to customers, e.g. 'Same day'", max_length=60)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Rider zones only: furthest straight-line distance from the dispatch point this fee covers.', max_digits=6, null=True)),
                ('address', models.CharField(blank=True, help_text='Store pickup only: where to collect.', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'fee'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Store pickup'), ('rider', 'Rider delivery'), ('agent', 'Pickup agent (e.g. Pickup Mtaani)')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Courier/agent parcel code, shown to the customer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Being prepared'), ('ready_for_pickup', 'Ready for pickup'), ('out_for_delivery', 'Out for delivery'), ('shipped', 'Sent to pickup agent'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryoption'),
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Being prepared'), ('ready_for_pickup', 'Ready for pickup'), ('out_for_delivery', 'Out for delivery'), ('shipped', 'Sent to pickup agent'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
