# Generated by Django 6.0.7 on 2026-10-09 00:41

import apps.consultations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('herbal_coach', 'Herbal coach'), ('medical_specialist', 'Medical specialist')], max_length=20)),
                ('title', models.CharField(help_text="e.g. 'Clinical Herbalist' or 'General Practitioner'", max_length=150)),
                ('photo_url', models.URLField(blank=True, help_text='Public https link to a square photo.')),
                ('bio', models.TextField()),
                ('specialties', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Digestion, Sleep'", max_length=255)),
                ('languages', models.CharField(default='English, Swahili', max_length=100)),
                ('licence_number', models.CharField(blank=True, help_text='Required for medical specialists (KMPDC registration number).', max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('session_minutes', models.PositiveIntegerField(default=30)),
                ('offers_whatsapp', models.BooleanField(default=True)),
                ('offers_phone', models.BooleanField(default=True)),
                ('offers_video', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, help_text='Private. New paid bookings are emailed here.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=apps.consultations.models.generate_consultation_reference, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Paid — awaiting scheduling'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20)),
                ('mode', models.CharField(choices=[('whatsapp', 'WhatsApp chat'), ('phone', 'Phone call'), ('video', 'Video call')], max_length=10)),
                ('preferred_time', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('concern', models.TextField()),
                ('consent_given_at', models.DateTimeField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='The confirmed session time.', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Video calls: the link the customer should join.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='consultations.expert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
